# Generated by Django 4.2.7 on 2023-11-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('purchased', 'Purchased')], default='available', max_length=20),
        ),
    ]
