# Generated by Django 4.2.7 on 2023-11-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_ticket_buyer_ticket_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='quantity',
            new_name='total_quantity',
        ),
        migrations.AddField(
            model_name='ticket',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
