# Generated by Django 4.2.7 on 2023-11-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_quantity_ticket_total_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='remaining_quantity',
            new_name='sold_quantity',
        ),
    ]
