# Generated by Django 4.2.7 on 2023-11-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_ticket_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='creator',
        ),
        migrations.AddField(
            model_name='ticket',
            name='creator_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
