# Generated by Django 4.2.7 on 2023-11-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Event Provider'), (3, 'Admin')], default=1),
        ),
    ]
