# Generated by Django 4.2.7 on 2023-11-23 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('seminar', 'Seminar'), ('workshop', 'Workshop'), ('concert', 'Concert'), ('exhibition', 'Exhibition'), ('networking', 'Networking Event'), ('meetup', 'Meetup'), ('party', 'Party'), ('wedding', 'Wedding'), ('sports', 'Sports Event'), ('fundraiser', 'Fundraiser'), ('webinar', 'Webinar'), ('hackathon', 'Hackathon'), ('launch', 'Product Launch'), ('training', 'Training'), ('award_ceremony', 'Award Ceremony'), ('art_show', 'Art Show'), ('book_signing', 'Book Signing'), ('film_screening', 'Film Screening'), ('food_tasting', 'Food Tasting'), ('festival', 'Festival'), ('charity', 'Charity Event'), ('community', 'Community Event'), ('other', 'Other')], default='conference', max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_events', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
