# Generated by Django 4.2.7 on 2023-11-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='buyer',
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
