# Generated by Django 4.2.7 on 2023-11-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('VIP', 'VIP')], default='Regular', max_length=50),
        ),
    ]
