# Generated by Django 4.2.7 on 2023-11-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_ticket_sold_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creator_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
